# Generated by Django 3.0.5 on 2020-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('resume', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('applyid', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
